name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        toolchain: ['1.77', stable]
        runs-on: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.runs-on }}

    steps:
    - uses: actions/checkout@v2
    - name: Install ${{ matrix.toolchain }}
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: ${{ matrix.toolchain }}
        override: true
    - name: Use MSRV Cargo.lock
      run: cp Cargo.lock.msrv Cargo.lock
      if: matrix.toolchain == '1.77'
    # Install openssl through vcpkg from rust-openssl github CI
    - run: echo "VCPKG_ROOT=$env:VCPKG_INSTALLATION_ROOT" | Out-File -FilePath $env:GITHUB_ENV -Append
      if: matrix.runs-on == 'windows-latest'
    - run: vcpkg install openssl:x64-windows-static-md
      if: matrix.runs-on == 'windows-latest'
    - name: Build
      run: cargo build --verbose
    - name: Build (without default features)
      run: cargo build --verbose --no-default-features
    - name: Build with --features "std"
      run: cargo build --verbose --no-default-features --features "std"
    - name: Build with --features "openssl"
      run: cargo build --verbose --no-default-features --features "openssl"
    - name: Build with --features "rustls"
      run: cargo build --verbose --no-default-features --features "rustls"
  test:
    strategy:
      matrix:
        runs-on: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.runs-on }}
    steps:
    - uses: actions/checkout@v2
    # Install openssl through vcpkg (from rust-openssl github CI)
    - run: echo "VCPKG_ROOT=$env:VCPKG_INSTALLATION_ROOT" | Out-File -FilePath $env:GITHUB_ENV -Append
      if: matrix.runs-on == 'windows-latest'
    - run: vcpkg install openssl:x64-windows-static-md
      if: matrix.runs-on == 'windows-latest'
    - name: Run tests
      run: cargo test --verbose --all-features
  clippy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: clippy
      run: cargo clippy --verbose -- -Dwarnings
