name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        toolchain: ['1.80', stable]
        runs-on: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.runs-on }}

    steps:
    - uses: actions/checkout@v2
    - name: Install ${{ matrix.toolchain }}
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: ${{ matrix.toolchain }}
        override: true
    - name: Use MSRV Cargo.lock
      run: cp Cargo.lock.msrv Cargo.lock
      if: matrix.toolchain == '1.80'
    # Install openssl through vcpkg from rust-openssl github CI
    - run: echo "VCPKG_ROOT=$env:VCPKG_INSTALLATION_ROOT" | Out-File -FilePath $env:GITHUB_ENV -Append
      if: matrix.runs-on == 'windows-latest'
    - run: vcpkg install openssl:x64-windows-static-md
      if: matrix.runs-on == 'windows-latest'
    - name: Build
      run: cargo build --workspace --verbose --exclude turn-fuzz
    - name: Build (without default features)
      run: cargo build --verbose --no-default-features
    - name: Build with --features "std"
      run: cargo build --workspace --verbose --exclude turn-fuzz --no-default-features --features "std"
    - name: Build separate crates
      run: for d in examples turn-client-dimpl turn-server-dimpl; do pushd "$d"; cargo build --verbose; popd; done
      if: matrix.toolchain == 'stable' && matrix.runs-on != 'windows-latest'
    - name: Build separate crates
      run: foreach ($d in @('examples','turn-client-dimpl','turn-server-dimpl')) { pushd "$d"; cargo build --verbose; popd }
      if: matrix.toolchain == 'stable' && matrix.runs-on == 'windows-latest'
  test:
    strategy:
      matrix:
        runs-on: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.runs-on }}
    steps:
    - uses: actions/checkout@v2
    # Install openssl through vcpkg (from rust-openssl github CI)
    - run: echo "VCPKG_ROOT=$env:VCPKG_INSTALLATION_ROOT" | Out-File -FilePath $env:GITHUB_ENV -Append
      if: matrix.runs-on == 'windows-latest'
    - run: vcpkg install openssl:x64-windows-static-md
      if: matrix.runs-on == 'windows-latest'
    - name: Run tests
      run: cargo test --workspace --verbose --all-features
    - name: Run tests (separate crates)
      run: for d in examples turn-client-dimpl turn-server-dimpl; do pushd "$d"; cargo test --verbose --all-features; popd; done
      if: matrix.runs-on != 'windows-latest'
    - name: Run tests (separate crates)
      run: foreach ($d in @('examples','turn-client-dimpl','turn-server-dimpl')) { pushd "$d"; cargo test --verbose --all-features; popd }
      if: matrix.runs-on == 'windows-latest'
    - name: Build benchmarks
      run: cargo bench --workspace --no-run --verbose --exclude turn-fuzz
    - name: Build benchmarks (separate crates)
      run: for d in examples turn-client-dimpl turn-server-dimpl; do pushd "$d"; cargo bench --no-run --verbose; popd; done
      if: matrix.runs-on != 'windows-latest'
    - name: Build benchmarks (separate crates)
      run: foreach ($d in @('examples','turn-client-dimpl','turn-server-dimpl')) { pushd "$d"; cargo bench --no-run --verbose; popd }
      if: matrix.runs-on == 'windows-latest'
  clippy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: clippy
      run: cargo clippy --verbose -- -Dwarnings
    - name: clippy (separate crates)
      run: for d in examples turn-client-dimpl turn-server-dimpl; do pushd "$d"; cargo clippy --verbose -- -Dwarnings; popd; done
